### ISSUE TITLE
Config file overrides are obscure

### ISSUE THREAD

**Issue by Seldaek** [saz/puppet-php#4]
This is probably partly due to my lack of experience with puppet, but I find the rules to override configs are quite impossible to follow.

For example `php::conf` defines this:

```
    source  => $source ? {
        undef   => undef,
        true    => [
            "puppet:///files/${fqdn}/etc/php5/conf.d/${file_name}",
            "puppet:///files/${hostgroup}/etc/php5/conf.d/${file_name}",
            "puppet:///files/${domain}/etc/php5/conf.d/${file_name}",
            "puppet:///files/global/etc/php5/conf.d/${file_name}",
        ],
        default => "${source}${file_name}",
    },
```

Which forced me to use this to get the file I wanted to be included:

```
php::conf { "nelmio":
    source => "puppet:///modules/nelmio/",
    notify => Class['php::fpm::service'],
}
```

You see that I specify an incomplete source, and then the name of the file, so it picks `nelmio.ini`. I can't directly specify the source I want, which is non-obvious unless you read the sources. If it's possible to make it accept complete file paths as-is in addition to the current magic method, it would be great.

Now I realize that I could just have used a complete file definition myself instead of relying on yours, but I still think it's weird the way it's done (combining name + given source + some parameters).

**Comment by saz** [comment]
This should be fixed with #6
