### ISSUE TITLE
No more symlinks from conf.d/ to */conf.d directories

### ISSUE THREAD

**Issue by willdurand** [saz/puppet-php#8]
Hi,

As commented here: https://github.com/saz/puppet-php/commit/7050a6f1d8821d279793dc0bd334a427127ce89d#commitcomment-2085150, I think there is an issue due to the `ensure` change.

With `ensure => directory`, it creates a directory which is empty as all `.ini` files are located in the "base" `conf.d/` directory. 

With `ensure => "../conf.d"` it creates the "base" `conf.d` directory will all `.ini` files (as usual) but also creates symlinks from this directory to all `conf.d` in all available php configs (cli, fpm, etc.)

Reverting the changes fix this issue.

William

**Comment by saz** [comment]
Sorry for the inconvenience caused by this bug. It's fixed and much cleaner now.

I'll write tests for this module asap, to avoid such mistakes in the future.

**Comment by willdurand** [comment]
Thank you!
